/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.desktop.disciplina;

import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.pojo.Disciplina;
import view.desktop.TelaPrincipal;

/**
 *
 * @author Elias Júnior
 */
public class TelaInformacoesDisciplina extends javax.swing.JFrame {

    TelaPrincipal telaPrincipal;

    /**
     * Creates new form TelaInformacoesDisciplina
     */
    public TelaInformacoesDisciplina(TelaPrincipal telaPrincipal) {
        initComponents();
        this.carregarListaDisciplinas();
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DisciplinaLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DisciplinaValue = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        InfoIdLabel = new javax.swing.JLabel();
        InfoIdValue = new javax.swing.JLabel();
        InfoNomeLabel = new javax.swing.JLabel();
        InfoNomeValue = new javax.swing.JLabel();
        InfoEmentaLabel = new javax.swing.JLabel();
        InfoEmentaValue = new javax.swing.JLabel();
        InfoCargaHorariaLabel = new javax.swing.JLabel();
        InfoCargaHorariaValue = new javax.swing.JLabel();
        InfoTurmasLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TurmasValue = new javax.swing.JTable();
        ProfessorAptoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProfessoresAptosValue = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações da disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        DisciplinaLabel.setText("Disciplina:");

        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        InfoIdLabel.setText("ID:");

        InfoNomeLabel.setText("Nome:");

        InfoEmentaLabel.setText("Ementa:");

        InfoCargaHorariaLabel.setText("Carga horária:");

        InfoTurmasLabel.setText("Turmas:");

        TurmasValue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ano", "Período", "Professor", "Horário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TurmasValue);

        ProfessorAptoLabel.setText("Professores aptos:");

        ProfessoresAptosValue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ProfessoresAptosValue);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(InfoIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InfoIdValue))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(InfoNomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InfoNomeValue))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(InfoEmentaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InfoEmentaValue))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(InfoCargaHorariaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InfoCargaHorariaValue))
                    .addComponent(InfoTurmasLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(ProfessorAptoLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoIdLabel)
                    .addComponent(InfoIdValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoNomeLabel)
                    .addComponent(InfoNomeValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoEmentaLabel)
                    .addComponent(InfoEmentaValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoCargaHorariaLabel)
                    .addComponent(InfoCargaHorariaValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoTurmasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProfessorAptoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DisciplinaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DisciplinaValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisciplinaLabel)
                    .addComponent(jButton1)
                    .addComponent(DisciplinaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (this.telaPrincipal != null) {
            this.telaPrincipal.setInitData();
            this.telaPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String disciplinaStr = (String) this.DisciplinaValue.getSelectedItem();
        if (disciplinaStr == null) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar uma disciplina antes.");
        } else {
            long disciplinaId = Long.parseLong(disciplinaStr.split(":")[0]);
            Disciplina disciplina = TelaPrincipal.disciplinaDao.findDisciplina(disciplinaId);
            limparPainelDisciplina();
            if (disciplina == null) {
                JOptionPane.showMessageDialog(this, "A disciplina selecionada não foi encontrada.");
            } else {
                this.carregarPainelDisciplina(disciplina);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carregarPainelDisciplina(Disciplina disciplina) {
        DefaultTableModel dtmProfessores = (DefaultTableModel) this.ProfessoresAptosValue.getModel();
        DefaultTableModel dtmTurmas = (DefaultTableModel) this.TurmasValue.getModel();
        this.InfoCargaHorariaValue.setText(String.valueOf(disciplina.getCargaHoraria()));
        this.InfoEmentaValue.setText(disciplina.getEmenta());
        this.InfoIdValue.setText(String.valueOf(disciplina.getId()));
        this.InfoNomeValue.setText(disciplina.getNome());
        disciplina.getTurmas().forEach((t) -> {
            dtmTurmas.addRow(new Object[]{t.getId(), t.getAno(), t.getPeriodo(), t.getProfessor().getNome(), t.getHorario()});
        });
        disciplina.getProfessoresAptos().forEach((p) -> {
            dtmProfessores.addRow(new Object[]{p.getId(), p.getNome(), p.getCpf()});
        });
    }

    private void limparComboBox(DefaultTableModel dtm) {
        int tam = dtm.getRowCount();
        for (int i = 0; i < tam; i++) {
            dtm.removeRow(i);
        }
    }

    private void limparPainelDisciplina() {
        DefaultTableModel dtmProfessores = (DefaultTableModel) this.ProfessoresAptosValue.getModel();
        DefaultTableModel dtmTurmas = (DefaultTableModel) this.TurmasValue.getModel();
        this.limparComboBox(dtmTurmas);
        this.limparComboBox(dtmProfessores);
        this.InfoCargaHorariaValue.setText("");
        this.InfoEmentaValue.setText("");
        this.InfoIdValue.setText("");
        this.InfoNomeValue.setText("");
    }

    private void carregarListaDisciplinas() {
        this.DisciplinaValue.removeAllItems();
        List<Disciplina> disciplinas = TelaPrincipal.disciplinaDao.findDisciplinaEntities();
        DefaultComboBoxModel comboBoxDisciplinas = new javax.swing.DefaultComboBoxModel();
        disciplinas.forEach((d) -> {
            String nome = d.getId() + ": " + d.getNome();
            comboBoxDisciplinas.addElement(nome);
        });
        this.DisciplinaValue.setModel(comboBoxDisciplinas);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisciplinaLabel;
    private javax.swing.JComboBox DisciplinaValue;
    private javax.swing.JLabel InfoCargaHorariaLabel;
    private javax.swing.JLabel InfoCargaHorariaValue;
    private javax.swing.JLabel InfoEmentaLabel;
    private javax.swing.JLabel InfoEmentaValue;
    private javax.swing.JLabel InfoIdLabel;
    private javax.swing.JLabel InfoIdValue;
    private javax.swing.JLabel InfoNomeLabel;
    private javax.swing.JLabel InfoNomeValue;
    private javax.swing.JLabel InfoTurmasLabel;
    private javax.swing.JLabel ProfessorAptoLabel;
    private javax.swing.JTable ProfessoresAptosValue;
    private javax.swing.JTable TurmasValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
