/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.desktop.turma;

import java.awt.event.WindowEvent;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.pojo.Disciplina;
import model.pojo.Professor;
import model.pojo.Turma;
import view.desktop.TelaPrincipal;

/**
 *
 * @author Elias Júnior
 */
public class TelaCadastrarTurma extends javax.swing.JFrame {

    TelaPrincipal telaPrincipal;

    /**
     * Creates new form TelaCadastrarTurma
     *
     * @param telaPrincipal
     */
    public TelaCadastrarTurma(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
    }

    private void closeFrame() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSED));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AnoLabel = new javax.swing.JLabel();
        AnoValue = new javax.swing.JTextField();
        PeriodoLabel = new javax.swing.JLabel();
        PeriodoValue = new javax.swing.JTextField();
        LocalLabel = new javax.swing.JLabel();
        LocalValue = new javax.swing.JTextField();
        VagasLabel = new javax.swing.JLabel();
        VagasValue = new javax.swing.JTextField();
        HorarioLabel = new javax.swing.JLabel();
        HorarioValue = new javax.swing.JTextField();
        ProfessorLabel = new javax.swing.JLabel();
        ProfessorValue = new javax.swing.JComboBox();
        DisciplinaLabel = new javax.swing.JLabel();
        DisciplinaValue = new javax.swing.JComboBox();
        CadastrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar turma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        AnoLabel.setText("Ano:");

        PeriodoLabel.setText("Período:");

        LocalLabel.setText("Local:");

        VagasLabel.setText("Número de vagas:");

        HorarioLabel.setText("Horário:");

        ProfessorLabel.setText("Professor:");

        List<Professor> professores = TelaPrincipal.professorDao.findProfessorEntities();
        DefaultComboBoxModel comboBoxProfessores = new javax.swing.DefaultComboBoxModel();
        professores.forEach((p) -> {
            String nome = p.getId() + ": " + p.getNome();
            comboBoxProfessores.addElement(nome);
        });
        ProfessorValue.setModel(comboBoxProfessores);

        DisciplinaLabel.setText("Disciplina:");

        List<Disciplina> disciplinas = TelaPrincipal.disciplinaDao.findDisciplinaEntities();
        DefaultComboBoxModel comboBoxDisciplinas = new javax.swing.DefaultComboBoxModel();
        disciplinas.forEach((d) -> {
            String nome = d.getId() + ": " + d.getNome();
            comboBoxDisciplinas.addElement(nome);
        });
        DisciplinaValue.setModel(comboBoxDisciplinas);

        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AnoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AnoValue))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PeriodoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PeriodoValue))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LocalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocalValue))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VagasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VagasValue, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HorarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HorarioValue))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ProfessorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProfessorValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DisciplinaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DisciplinaValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CadastrarButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnoLabel)
                    .addComponent(AnoValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PeriodoLabel)
                    .addComponent(PeriodoValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalLabel)
                    .addComponent(LocalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VagasLabel)
                    .addComponent(VagasValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HorarioLabel)
                    .addComponent(HorarioValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfessorLabel)
                    .addComponent(ProfessorValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisciplinaLabel)
                    .addComponent(DisciplinaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastrarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (this.telaPrincipal != null) {
            this.telaPrincipal.setInitData();
            this.telaPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        try {
            String disciplinaStr = (String) this.DisciplinaValue.getSelectedItem();
            String professorStr = (String) this.ProfessorValue.getSelectedItem();
            if (disciplinaStr == null) {
                JOptionPane.showMessageDialog(this, "Você deve selecionar uma disciplina.");
                return;
            } else if (professorStr == null) {
                JOptionPane.showMessageDialog(this, "Você deve selecionar um professor.");
                return;
            }
            String[] disciplinaStrArray = disciplinaStr.split(":");
            String[] professorStrArray = professorStr.split(":");
            long disciplinaId = Long.parseLong(disciplinaStrArray[0]);
            long professorId = Long.parseLong(professorStrArray[0]);
            long ano = Long.parseLong(this.AnoValue.getText());
            long periodo = Long.parseLong(this.PeriodoValue.getText());
            String local = this.LocalValue.getText();
            long numVagas = Long.parseLong(this.VagasValue.getText());
            String horario = this.HorarioValue.getText();
            Disciplina disciplina = TelaPrincipal.disciplinaDao.findDisciplina(disciplinaId);
            Professor professor = TelaPrincipal.professorDao.findProfessor(professorId);
            if (disciplina == null) {
                JOptionPane.showMessageDialog(this, "Disciplina não encontrada.");
            } else if (professor == null) {
                JOptionPane.showMessageDialog(this, "Professor não encontrado.");
            } else if (!professor.getDisciplinasApto().contains(disciplina)) {
                JOptionPane.showMessageDialog(this, "Este professor não está apto para a disciplina informada.");
            } else {
                Turma turma = new Turma(ano, periodo, local, numVagas, horario, disciplina, professor);
                TelaPrincipal.turmaDao.create(turma);
                int resposta = JOptionPane.showConfirmDialog(this, "A turma foi cadastrada. Deseja cadastrar outra?");
                switch (resposta) {
                    case 0:
                        this.AnoValue.setText("");
                        this.PeriodoValue.setText("");
                        this.LocalValue.setText("");
                        this.VagasValue.setText("");
                        this.HorarioValue.setText("");
                        break;
                    default:
                        this.closeFrame();
                        break;
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Há um erro com o formato de um dos valores numéricos.");
        }
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnoLabel;
    private javax.swing.JTextField AnoValue;
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JLabel DisciplinaLabel;
    private javax.swing.JComboBox DisciplinaValue;
    private javax.swing.JLabel HorarioLabel;
    private javax.swing.JTextField HorarioValue;
    private javax.swing.JLabel LocalLabel;
    private javax.swing.JTextField LocalValue;
    private javax.swing.JLabel PeriodoLabel;
    private javax.swing.JTextField PeriodoValue;
    private javax.swing.JLabel ProfessorLabel;
    private javax.swing.JComboBox ProfessorValue;
    private javax.swing.JLabel VagasLabel;
    private javax.swing.JTextField VagasValue;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
