/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.desktop;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import model.dao.AlunoDao;
import model.dao.AtividadeDao;
import model.dao.DisciplinaDao;
import model.dao.FaltaDao;
import model.dao.NotaDao;
import model.dao.ProfessorDao;
import model.dao.TurmaDao;
import model.dao.jpa.AlunoDaoJpa;
import model.dao.jpa.AtividadeDaoJpa;
import model.dao.jpa.DisciplinaDaoJpa;
import model.dao.jpa.FaltaDaoJpa;
import model.dao.jpa.NotaDaoJpa;
import model.dao.jpa.ProfessorDaoJpa;
import model.dao.jpa.TurmaDaoJpa;
import model.pojo.Turma;
import view.desktop.aluno.TelaCadastrarAluno;
import view.desktop.aluno.TelaDeletarAluno;
import view.desktop.professor.TelaCadastrarProfessor;
import view.desktop.professor.TelaDeletarProfessor;

/**
 *
 * @author Elias Júnior
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("eliasjnior");
    public static final AlunoDao alunoDao = new AlunoDaoJpa(emf);
    public static final DisciplinaDao disciplinaDao = new DisciplinaDaoJpa(emf);
    public static final FaltaDao faltaDao = new FaltaDaoJpa(emf);
    public static final NotaDao notaDao = new NotaDaoJpa(emf);
    public static final ProfessorDao professorDao = new ProfessorDaoJpa(emf);
    public static final TurmaDao turmaDao = new TurmaDaoJpa(emf);
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setInitData();
    }
    
    /**
     * Define o conteúdo inicial da tela
     */
    public void setInitData() {
        this.AlunosCadastradosValue.setText(String.valueOf(TelaPrincipal.alunoDao.getAlunoCount()));
        this.DisciplinasCadastradasValue.setText(String.valueOf(TelaPrincipal.disciplinaDao.getDisciplinaCount()));
        this.ProfessoresCadastradosValue.setText(String.valueOf(TelaPrincipal.professorDao.getProfessorCount()));
        this.TurmasCadastradasValue.setText(String.valueOf(TelaPrincipal.turmaDao.getTurmaCount()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEstatisticas = new javax.swing.JPanel();
        AlunosCadastradosLabel = new javax.swing.JLabel();
        AlunosCadastradosValue = new javax.swing.JLabel();
        ProfessoresCadastradosLabel = new javax.swing.JLabel();
        ProfessoresCadastradosValue = new javax.swing.JLabel();
        DisciplinasCadastradasLabel = new javax.swing.JLabel();
        DisciplinasCadastradasValue = new javax.swing.JLabel();
        TurmasCadastradasLabel = new javax.swing.JLabel();
        TurmasCadastradasValue = new javax.swing.JLabel();
        PainelInstrucoes = new javax.swing.JPanel();
        instrucoesLinha1 = new javax.swing.JLabel();
        instrucoesLinha2 = new javax.swing.JLabel();
        instrucoesLinha3 = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuAluno = new javax.swing.JMenu();
        MenuCadastrarAluno = new javax.swing.JMenuItem();
        MenuDeletarAluno = new javax.swing.JMenuItem();
        MenuProfessor = new javax.swing.JMenu();
        MenuCadastrarProfessor = new javax.swing.JMenuItem();
        MenuDeletarProfessor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelEstatisticas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estatísticas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        AlunosCadastradosLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AlunosCadastradosLabel.setText("Alunos cadastrados:");

        AlunosCadastradosValue.setText("0");

        ProfessoresCadastradosLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ProfessoresCadastradosLabel.setText("Professores cadastrados:");

        ProfessoresCadastradosValue.setText("0");

        DisciplinasCadastradasLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DisciplinasCadastradasLabel.setText("Disciplinas cadastradas:");

        DisciplinasCadastradasValue.setText("0");

        TurmasCadastradasLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TurmasCadastradasLabel.setText("Turmas cadastradas:");

        TurmasCadastradasValue.setText("0");

        javax.swing.GroupLayout PanelEstatisticasLayout = new javax.swing.GroupLayout(PanelEstatisticas);
        PanelEstatisticas.setLayout(PanelEstatisticasLayout);
        PanelEstatisticasLayout.setHorizontalGroup(
            PanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstatisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstatisticasLayout.createSequentialGroup()
                        .addComponent(AlunosCadastradosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AlunosCadastradosValue))
                    .addGroup(PanelEstatisticasLayout.createSequentialGroup()
                        .addComponent(ProfessoresCadastradosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProfessoresCadastradosValue))
                    .addGroup(PanelEstatisticasLayout.createSequentialGroup()
                        .addComponent(DisciplinasCadastradasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DisciplinasCadastradasValue))
                    .addGroup(PanelEstatisticasLayout.createSequentialGroup()
                        .addComponent(TurmasCadastradasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TurmasCadastradasValue)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEstatisticasLayout.setVerticalGroup(
            PanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstatisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlunosCadastradosLabel)
                    .addComponent(AlunosCadastradosValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfessoresCadastradosLabel)
                    .addComponent(ProfessoresCadastradosValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisciplinasCadastradasLabel)
                    .addComponent(DisciplinasCadastradasValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TurmasCadastradasLabel)
                    .addComponent(TurmasCadastradasValue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelInstrucoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instruções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        instrucoesLinha1.setText("Seja bem vindo ao sistema de gerenciamento escolar. No menu superior você deve abrir a sessão que deseja, por exemplo:");
        instrucoesLinha1.setMaximumSize(new java.awt.Dimension(1024, 14));

        instrucoesLinha2.setText("Caso você queira gerenciar os alunos, como cadastrar, clique na aba \"Aluno\" e selecione \"Cadastrar aluno\". ");

        instrucoesLinha3.setText("Sempre que você realizar uma ação no programa, automaticamente ele será salvo e não será possível restaurar os dados anteriores.");

        javax.swing.GroupLayout PainelInstrucoesLayout = new javax.swing.GroupLayout(PainelInstrucoes);
        PainelInstrucoes.setLayout(PainelInstrucoesLayout);
        PainelInstrucoesLayout.setHorizontalGroup(
            PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instrucoesLinha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                        .addGroup(PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(instrucoesLinha2))
                            .addComponent(instrucoesLinha3))
                        .addGap(0, 334, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelInstrucoesLayout.setVerticalGroup(
            PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrucoesLinha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instrucoesLinha2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instrucoesLinha3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuAluno.setText("Aluno");

        MenuCadastrarAluno.setText("Cadastrar aluno");
        MenuCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarAlunoActionPerformed(evt);
            }
        });
        MenuAluno.add(MenuCadastrarAluno);

        MenuDeletarAluno.setText("Deletar aluno");
        MenuDeletarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeletarAlunoActionPerformed(evt);
            }
        });
        MenuAluno.add(MenuDeletarAluno);

        MenuPrincipal.add(MenuAluno);

        MenuProfessor.setText("Professor");

        MenuCadastrarProfessor.setText("Cadastrar professor");
        MenuCadastrarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarProfessorActionPerformed(evt);
            }
        });
        MenuProfessor.add(MenuCadastrarProfessor);

        MenuDeletarProfessor.setText("Deletar professor");
        MenuDeletarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeletarProfessorActionPerformed(evt);
            }
        });
        MenuProfessor.add(MenuDeletarProfessor);

        MenuPrincipal.add(MenuProfessor);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelInstrucoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarAlunoActionPerformed
        TelaCadastrarAluno cadastrarAluno = new TelaCadastrarAluno(this);
        cadastrarAluno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuCadastrarAlunoActionPerformed

    private void MenuDeletarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeletarAlunoActionPerformed
        TelaDeletarAluno deletarAluno = new TelaDeletarAluno(this);
        deletarAluno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuDeletarAlunoActionPerformed

    private void MenuCadastrarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarProfessorActionPerformed
        TelaCadastrarProfessor cadastrarProfessor = new TelaCadastrarProfessor(this);
        cadastrarProfessor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuCadastrarProfessorActionPerformed

    private void MenuDeletarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeletarProfessorActionPerformed
        TelaDeletarProfessor deletarProfessor = new TelaDeletarProfessor(this);
        deletarProfessor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuDeletarProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlunosCadastradosLabel;
    private javax.swing.JLabel AlunosCadastradosValue;
    private javax.swing.JLabel DisciplinasCadastradasLabel;
    private javax.swing.JLabel DisciplinasCadastradasValue;
    private javax.swing.JMenu MenuAluno;
    private javax.swing.JMenuItem MenuCadastrarAluno;
    private javax.swing.JMenuItem MenuCadastrarProfessor;
    private javax.swing.JMenuItem MenuDeletarAluno;
    private javax.swing.JMenuItem MenuDeletarProfessor;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuProfessor;
    private javax.swing.JPanel PainelInstrucoes;
    private javax.swing.JPanel PanelEstatisticas;
    private javax.swing.JLabel ProfessoresCadastradosLabel;
    private javax.swing.JLabel ProfessoresCadastradosValue;
    private javax.swing.JLabel TurmasCadastradasLabel;
    private javax.swing.JLabel TurmasCadastradasValue;
    private javax.swing.JLabel instrucoesLinha1;
    private javax.swing.JLabel instrucoesLinha2;
    private javax.swing.JLabel instrucoesLinha3;
    // End of variables declaration//GEN-END:variables
}
